name: cjhamblin
favicon: null
layout_spectrum: 0.9673722740262747
typography_spectrum: 0.7378307266626507
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5182843843940645
  lightness: 0.7367065248545259
  saturation: 0.760108548682183
  rhythmicContrast: 0.5367901532445103
purpose: []
